--- 

- name: Install docker
  yum:
    name: docker
    state: latest

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Download docker-compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    
- name: Create symlink for docker-compose
  file: 
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    state: link
