Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", :type => 'dhcp', :adapter => 2
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.name = "firefly3-test"
      end
  end