--- 

- name: Create firefly3 directory
  file: 
    path: /root/firefly3
    owner: root
    group: root 
    state: directory

- name: Template docker-compose files
  template:
    src: "{{ item.src }}"
    dest: "/root/firefly3/{{ item.dest }}"
    owner: root 
    group: root 
  loop:
    - { src: docker-compose.yml.j2, dest: docker-compose.yml }
    - { src: env.config.j2, dest: .env }

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewalld
  firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    zone: public
  notify: reload firewalld

- name: Start firefly
  command: "docker-compose up -d"
  args:
    chdir: /root/firefly3

- name: Output firefly url
  debug:
    msg: "Firefly3 URL: http://{{ ansible_enp0s8.ipv4.address }}/"